-- MySQL Script generated by MySQL Workbench
-- 11/14/15 11:38:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hiragana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hiragana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hiragana` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hiragana` ;

-- -----------------------------------------------------
-- Table `hiragana`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiragana`.`user` (
  `email` VARCHAR(40) NOT NULL,
  `nickname` VARCHAR(20) NOT NULL,
  `pwd_hash` CHAR(32) NULL,
  `pwd_salt` CHAR(16) NULL,
  `t_registered` DATETIME NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiragana`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiragana`.`course` (
  `course_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(40) NULL,
  `name_de` VARCHAR(40) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiragana`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiragana`.`lesson` (
  `lesson_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `lesson_nr` INT UNSIGNED NOT NULL,
  `name_en` VARCHAR(40) NULL,
  `name_de` VARCHAR(40) NULL,
  `points` INT UNSIGNED NULL,
  `t_added` DATETIME NULL,
  INDEX `ind_course_id_3324` (`course_id` ASC),
  PRIMARY KEY (`lesson_id`),
  CONSTRAINT `fk_lesson_course_23423`
    FOREIGN KEY (`course_id`)
    REFERENCES `hiragana`.`course` (`course_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiragana`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiragana`.`exercise` (
  `exercise_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lesson_id` INT UNSIGNED NOT NULL,
  `question` VARCHAR(50) NULL,
  `answer_en` VARCHAR(50) NULL,
  `answer_de` VARCHAR(45) NULL,
  PRIMARY KEY (`exercise_id`),
  INDEX `fk_excercise_lesson_8733_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_excercise_lesson_8733`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `hiragana`.`lesson` (`lesson_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiragana`.`user_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiragana`.`user_lesson` (
  `email` VARCHAR(40) NOT NULL,
  `lesson_id` INT UNSIGNED NOT NULL,
  `t_started` DATETIME NOT NULL,
  `t_completed` DATETIME NULL,
  PRIMARY KEY (`email`, `lesson_id`, `t_started`),
  INDEX `fk_user_lesson_lesson_2343_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_user_lesson_user_4384`
    FOREIGN KEY (`email`)
    REFERENCES `hiragana`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_lesson_lesson_2343`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `hiragana`.`lesson` (`lesson_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiragana`.`user_exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiragana`.`user_exercise` (
  `email` VARCHAR(40) NOT NULL,
  `exercise_id` INT UNSIGNED NOT NULL,
  `t_answered` VARCHAR(45) NOT NULL,
  `correct` TINYINT(1) NULL,
  PRIMARY KEY (`email`, `exercise_id`, `t_answered`),
  INDEX `fk_user_exercise_exercise_idx` (`exercise_id` ASC),
  CONSTRAINT `fk_user_exercise_user_4384`
    FOREIGN KEY (`email`)
    REFERENCES `hiragana`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_exercise_exercise_3849`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `hiragana`.`exercise` (`exercise_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hiragana`.`course`
-- -----------------------------------------------------
START TRANSACTION;
USE `hiragana`;
INSERT INTO `hiragana`.`course` (`course_id`, `name_en`, `name_de`) VALUES (1, 'Japanese Foundation', 'Japanisch Grundkurs');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hiragana`.`lesson`
-- -----------------------------------------------------
START TRANSACTION;
USE `hiragana`;
INSERT INTO `hiragana`.`lesson` (`lesson_id`, `course_id`, `lesson_nr`, `name_en`, `name_de`, `points`, `t_added`) VALUES (1, 1, 1, 'Basic Expressions', 'Grundlegende Ausdrücke', 20, '2015-11-14 11:25:32');
INSERT INTO `hiragana`.`lesson` (`lesson_id`, `course_id`, `lesson_nr`, `name_en`, `name_de`, `points`, `t_added`) VALUES (2, 1, 2, 'Nationalities', 'Nationalitäten', 20, '2015-11-14 11:27:12');
INSERT INTO `hiragana`.`lesson` (`lesson_id`, `course_id`, `lesson_nr`, `name_en`, `name_de`, `points`, `t_added`) VALUES (3, 1, 3, 'Introducing yourself', 'Sich vorstellen', 30, '2015-11-14 11:28:46');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hiragana`.`exercise`
-- -----------------------------------------------------
START TRANSACTION;
USE `hiragana`;
INSERT INTO `hiragana`.`exercise` (`exercise_id`, `lesson_id`, `question`, `answer_en`, `answer_de`) VALUES (1, 1, 'Konnichiwa.', 'Hello', 'Hallo');
INSERT INTO `hiragana`.`exercise` (`exercise_id`, `lesson_id`, `question`, `answer_en`, `answer_de`) VALUES (2, 1, 'Ohayō gozaimasu.', 'Good morning', 'Guten Morgen');
INSERT INTO `hiragana`.`exercise` (`exercise_id`, `lesson_id`, `question`, `answer_en`, `answer_de`) VALUES (3, 1, 'Konbanwa.', 'Good evening', 'Guten Abend');
INSERT INTO `hiragana`.`exercise` (`exercise_id`, `lesson_id`, `question`, `answer_en`, `answer_de`) VALUES (4, 1, 'Oyasuminasai.', 'Good night', 'Gute Nacht');
INSERT INTO `hiragana`.`exercise` (`exercise_id`, `lesson_id`, `question`, `answer_en`, `answer_de`) VALUES (5, 1, 'Sayōnara.', 'Goodbye', 'Auf Wiedersehen');

COMMIT;

